# Generated by Django 5.2.2 on 2025-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_cart_cartitem_paintproduct_category_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
