# Generated by Django 5.2.2 on 2025-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_paintproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
