# Generated by Django 5.2.2 on 2025-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_paintproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('En préparation', 'En préparation'), ('Expédiée', 'Expédiée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20),
        ),
    ]
