# Generated by Django 5.2.2 on 2025-06-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_paintproduct_gamme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintproduct',
            name='gamme',
            field=models.CharField(choices=[('luxe', 'Gamme de Luxe'), ('pro', 'Gamme Pro'), ('eco', 'Gamme Économique')], default='pro', max_length=10, verbose_name='Gamme'),
        ),
    ]
