# Generated by Django 5.2.2 on 2025-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_paintproduct_gamme'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintproduct',
            name='lessivage',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Lessivage'),
        ),
    ]
