# Generated by Django 5.2.2 on 2025-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_paintproduct_lessivage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintproduct',
            name='colissage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Colissage (kg)'),
        ),
    ]
